# Generated by Django 6.0.6 on 2026-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Hostel Essentials', 'Hostel Essentials'), ('Cycles', 'Cycles'), ('Study Material', 'Study Material')], max_length=50)),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('borrow', 'Borrow'), ('free', 'Free')], default='sell', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20)),
                ('program', models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('PhD', 'PhD')], max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=100)),
                ('campus', models.CharField(default='NIT Durgapur', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('is_negotiable', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
